---
title: "Garren"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Garren}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(wrta)
library(sf)
library(dplyr)
library(rgdal)
library(ggplot2)
```



```{r, warning = FALSE, message = FALSE }
ridership <- system.file("extdata/Weekday_ridership.xlsx", package = "wrta") %>% 
  readxl::read_excel() 

county <- system.file("extdata/tl_2017_25027_faces/tl_2017_25027_faces.shp",
                     package = "wrta") %>% st_read()

roads <- system.file("extdata/tl_2018_25027_roads/tl_2018_25027_roads.shp",
                     package = "wrta") %>% st_read()

stops <- system.file("extdata/WRTA_August_2020/Active_WRTA_Bus_Stops_Aug2020.shp",
                     package = "wrta") %>% st_read()

routes <- system.file("extdata/WRTA_August_2020/Active_WRTA_Routes_Aug2020.shp",
                      package = "wrta") %>% st_read() %>% st_zm()

worcester <- system.file("extdata/Worcester/worcester.shp",
                     package = "wrta") %>% st_read()

```

#Cropping
```{r, warning = FALSE, message = FALSE}
#reproject
routes <- st_transform(x = routes, crs = st_crs(worcester))

stops <- st_transform(x = stops,crs = st_crs(worcester))

roads <- st_transform(x = roads, crs = st_crs(worcester))

#major roads in Worcester
roads_worc <- st_intersection(x = roads, y = worcester) 
#bus stops
stops_worc <- st_intersection(x = stops, y = worcester)
#bus routes
routes_worc <- st_intersection(x = routes, y = worcester)

```
# Join
```{r, warning = FALSE, message = FALSE}
#Identifying whether variables Match
routes$Bus_Route %in% ridership$ROUTE

#completing a join via coercion
routes_ridership <- right_join(x = ridership, 
                               y = routes_worc, by = c("ROUTE" = "BusRoute")) 
```

## Categories Map
```{r, warning = FALSE, message = FALSE, error = TRUE}
#cleaning data up
distinct_routes <- routes_ridership %>% distinct(ROUTE, .keep_all = TRUE) 

#generating a new field to categorize ridership
distinct_routes_filter$ride_cat
distinct_routes_filter <- distinct_routes %>% 
  mutate(ride_cat = ifelse(WKDAY_RIDERS > 170000, "high", "other"), 
         ride_cat = ifelse(between(WKDAY_RIDERS, 10000, 170000), "medium", ride_cat),
         ride_cat = ifelse(WKDAY_RIDERS < 10000, "low", ride_cat)) %>% 
  st_as_sf()
```


```{r, warning = FALSE, message = FALSE}
# uh oh it isn't displaying properly, let's break that up

distinct_route_filter_low <- subset(distinct_routes_filter, ride_cat == "low", select = c("geometry")) 

distinct_route_filter_medium <- subset(distinct_routes_filter, ride_cat == "medium", select = c("geometry"))

distinct_route_filter_high <- subset(distinct_routes_filter, ride_cat == "high", select = c("geometry"))
```


```{r, fig.width=4.75, fig.height=3.75, fig.align = "center"}
#plot
par(mar = c(0, 0, 1, 0))
plot(worcester %>% st_geometry(), col = "grey")
plot(distinct_route_filter_low %>% st_geometry(), col = "red", add = TRUE)
plot(distinct_route_filter_medium %>% st_geometry(), col = "yellow", add = TRUE)
plot(distinct_route_filter_high %>% st_geometry(), col = "green", add = TRUE)
title(main = "Routes Categorized by Ridership")
  
```

## Subsidies Map
```{r, warning = FALSE, message = FALSE, error = TRUE}
subsidy_routes_filter$sub_cat
subsidy_routes_filter <- distinct_routes %>% 
  mutate(sub_cat = ifelse(subsidy > 10.00, "high", "other"), 
         sub_cat = ifelse(between(subsidy, 3.00, 10.00), "medium", sub_cat),
         sub_cat = ifelse(subsidy < 3.00, "low", sub_cat)) %>% 
  st_as_sf()
```


```{r, warning = FALSE, message = FALSE}
subsidy_route_filter_low <- subset(subsidy_routes_filter, sub_cat == "low", select = c("geometry")) 

subsidy_route_filter_medium <- subset(subsidy_routes_filter, sub_cat == "medium", select = c("geometry"))

subsidy_route_filter_high <- subset(subsidy_routes_filter, sub_cat == "high", select = c("geometry"))
```


```{r, fig.width=4.75, fig.height=3.75, fig.align = "center"}
#plot
par(mar = c(0, 0, 1, 0))
plot(worcester %>% st_geometry(), col = "grey")
plot(subsidy_route_filter_low %>% st_geometry(), col = "green", add = TRUE)
plot(subsidy_route_filter_medium %>% st_geometry(), col = "yellow2", add = TRUE)
plot(subsidy_route_filter_high %>% st_geometry(), col = "red", add = TRUE)
title(main = "Routes Categorized by Subsidy")
legend(x = "bottomright", legend = c("low", "medium", "high"), 
       fill = c("green", "yellow2", "red"), bty = "n")

```


## Headways Map

```{r, warning = FALSE, message = FALSE, error = TRUE}
headways_routes_filter$head_cat
headways_routes_filter <- distinct_routes %>% 
  mutate(head_cat = ifelse(time > 60, "high", "other"), 
         head_cat = ifelse(between(time, 30, 60), "medium", head_cat),
         head_cat = ifelse(time < 30, "low", head_cat)) %>% 
  st_as_sf()
```


```{r, warning = FALSE, message = FALSE}
headways_route_filter_low <- subset(headways_routes_filter, head_cat == "low", select = c("geometry")) 

headways_route_filter_medium <- subset(headways_routes_filter, head_cat == "medium", select = c("geometry"))

headways_route_filter_high <- subset(headways_routes_filter, head_cat == "high", select = c("geometry"))
```


```{r, fig.width=4.75, fig.height=3.75, fig.align = "center"}
par(mar = c(0, 0, 1, 0))
plot(worcester %>% st_geometry(), col = "grey")
plot(headways_route_filter_low %>% st_geometry(), col = "green", add = TRUE)
plot(headways_route_filter_medium %>% st_geometry(), col = "yellow2", add = TRUE)
plot(headways_route_filter_high %>% st_geometry(), col = "red", add = TRUE)
title(main = "Routes Categorized by Frequency of Service")
legend(x = "bottomright", legend = c("low", "medium", "high"), 
       fill = c("green", "yellow2", "red"), bty = "n")

```






