---
title: "Luke"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Luke}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
# Luke Watson-Sharer
# Population Density and Traffic Count Map
# Final Project Geog 246, with Garren
```{r, eval = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
```

```{r setup}
# Packages
library(dplyr)
library(ggplot2)
library(rgdal)
library(raster)
library(sf)
```

```{r, eval = FALSE}
# Read in files
# username fix
ridership <- system.file("extdata/Weekday_ridership.xlsx", package = "wrta") %>% 
  readxl::read_excel() 
county <- system.file("extdata/tl_2017_25027_faces/tl_2017_25027_faces.shp",
                     package = "wrta") %>% st_read()
roads <- system.file("extdata/tl_2018_25027_roads/tl_2018_25027_roads.shp",
                     package = "wrta") %>% st_read()
stops <- system.file("extdata/WRTA_August_2020/Active_WRTA_Bus_Stops_Aug2020.shp",
                     package = "wrta") %>% st_read()
routes <- system.file("extdata/WRTA_August_2020/Active_WRTA_Routes_Aug2020.shp",
                      package = "wrta") %>% st_read() %>% st_zm()
censusTractPolygon <- system.file("extdata/tl_2018_25027_roads/tl_2018_25027_roads.shp",
                     package = "wrta") %>% st_read()
polygonCensusTract<- system.file("extdata/Census/export-gisdata.mapc.census2010_tracts_poly.shp",
                     package = "wrta") %>% st_read()

vehicle <- system.file("extdata/tabular.trans_mavc_public_summary_ct_2014_q4.csv", package = "wrta") %>% readr::read_csv(.)

censusTractPop <- system.file("extdata/tabular.demo_general_demographics_ct_2010.csv", package = "wrta") %>% readr::read_csv(.)

worcester <- system.file("extdata/Worcester/worcester.shp",
                     package = "wrta") %>% st_read()
```

```{r, eval = FALSE}
# summary statistics and joins for setup
#Cropping
#reproject
routes_reprojected <- st_transform(x = routes, crs = st_crs(worcester))
stops_reprojected  <- st_transform(x = stops, crs = st_crs(worcester))
roads_reprojected  <- st_transform(x = roads, crs = st_crs(worcester))
#major roads in Worcester
roads_worc <- st_intersection(x = roads_reprojected , y = worcester) 
#bus stops
stops_worc <- st_intersection(x = stops_reprojected, y = worcester)
#bus routes
routes_worc <- st_intersection(x = routes_reprojected, y = worcester)
censusTractDataFram1 <- left_join(censusTractPop, vehicle, by = "ct10_id") 
st)
censusDataVPOP <- polygonCensusTract %>%  
    mutate(ct10_id = as.numeric(ct10_id))
censusDataVPOPPoly <- left_join(censusDataVPOP, censusTractDataFram1, by = "ct10_id") #joining new dataset
worcester_census <- st_intersection(x = censusDataVPOPPoly, y = worcester) 
popDensityTable <- worcester_census[ , c("pop", "area_acres", "area_sqft", "ct10_id", "objectid", "shape")] 
popDensityTable
vehicleDensityTable <- worcester_census[ , c("veh_tot", "area_acres", "area_sqft", "ct10_id", "objectid", "shape")] 
vehicleDensityTable
popDensityTable$density_acres <- (popDensityTable$pop/640) # density over acre mile
popDensityTable$density_sqmile <- (popDensityTable$pop/vehicleDensityTable$area_sqft) # density over sq mile
vehicleDensityTable$density_acres <- (vehicleDensityTable$veh_tot/640) # density over acre mile
vehicleDensityTable$density_sqmile <- (vehicleDensityTable$veh_tot/vehicleDensityTable$area_sqft) # density over sq mile
plot(vehicleDensityTable)
plot(popDensityTable)

vehicleDensityTable_subset <- subset(vehicleDensityTable, select = c("density_sqmile", "geometry"))
popDensityTable_subset <- subset(popDensityTable, select = c("density_sqmile", "geometry"))
mean(popDensityTable_subset$density_sqmile)
mean(vehicleDensityTable_subset$density_sqmile)
palletecolors <- colors()[1:3]
```

```{r, fig.width=4.75, fig.height=3.75, fig.align = "center"}
par(mar = c(0, 0, 1, 0))
set.seed(1)
Population_Density <- plot(popDensityTable_subset)
title("Density")
Vehicle_Density <- plot(vehicleDensityTable_subset)
title("Density")
```
